sudo: false
dist: trusty
language: node_js
env:
  - MONGODB_VERSION=3.4.x MONGODB_TOPOLOGY=standalone
  - MONGODB_VERSION=stable MONGODB_TOPOLOGY=standalone
  - MONGODB_VERSION=unstable MONGODB_TOPOLOGY=standalone
before_install:
  - npm i -g npm
install:
  - npm ci
script:
  - npm run check
  - npm test
cache:
  directories:
    - '$HOME/.npm'
    - node_modules
