sudo: false
dist: trusty
language: node_js
node_js:
  - 8.9.3
env:
  - MONGODB_VERSION=3.4.x MONGODB_TOPOLOGY=standalone
  - MONGODB_VERSION=3.4.x MONGODB_TOPOLOGY=cluster
  - MONGODB_VERSION=stable MONGODB_TOPOLOGY=standalone
  - MONGODB_VERSION=stable MONGODB_TOPOLOGY=cluster
  - MONGODB_VERSION=unstable MONGODB_TOPOLOGY=standalone
  - MONGODB_VERSION=unstable MONGODB_TOPOLOGY=cluster
before_install:
  - npm i -g npm
install:
  - npm ci
script:
  - npm run check
  - npm test
cache:
  directories:
    - '$HOME/.npm'
    - '$HOME/.nvm/versions/node/v8.9.3/lib/node_modules/npm'
