sudo: false
dist: trusty
language: node_js
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libkrb5-dev
      - xvfb
      - libsecret-1-dev
      - gnome-keyring
      - python-gnomekeyring
node_js:
  - 12.4.0
env:
  - MONGODB_VERSION=4.0.0 MONGODB_TOPOLOGY=standalone
before_install:
  - npm i -g npm
script:
  - npm run check
  - npm test
